project:
  type: website
  resources: 
    - "CNAME"

website:
  site-url: "https://eremrah.com/"
  description: "emraher"
  navbar:
    logo: "logo.png"
    search: false
    right:
    - text: "Home"
      href: index.qmd
    - text: "Teaching"
      href: teaching.qmd
    - text: "R"
      href: software.qmd
    - text: "Eviews"
      href: eviews.qmd
    - text: "usesthis"
      href: uses.qmd
    - text: '<i class="fab fa-github fa-lg"></i>'
      href: "https://github.com/emraher"
      aria-label: Github
      target: _blank
      rel: me
    - text: '<i class="fa-brands fa-bluesky"></i>'
      href: "https://bsky.app/profile/emraher.bsky.social"
      aria-label: Bluesky
      target: _blank
      rel: me
    - text: '<i class="fab fa-mastodon fa-lg"></i>'
      href: "https://econtwitter.net/@emraher"
      aria-label: Mastodon
      target: _blank
      rel: me
    - text: '<i class="fa-brands fa-x-twitter"></i>'
      href: "https://twitter.com/emrah_er"
      aria-label: Twitter
      target: _blank
      rel: me
    - text: '<i class="fab fa-keybase fa-lg"></i>'
      href: "https://keybase.io/emraher"
      aria-label: Keybase
      target: _blank
      rel: me



format:
  html:
    theme: [cosmo, styles.scss]
    toc: false
    minimal: true
    html-math-method: mathjax
    include-in-header: fontawesome.html
    mainfont: Merriweather
    monofont: JetBrains Mono
    fontsize: 1rem
    linestretch: 1.75
    