project:
  type: website
  resources:
    - "CNAME"
    - "keybase.txt"

website:
  title: "Emrah Er"
  site-url: "https://eremrah.com/"
  description: "emraher"
  navbar:
    search: false
    left:
    - text: '<i class="fa-solid fa-house fa-lg fa-fw"></i> Home'
      href: index.qmd
    - text: '<i class="fa-solid fa-person-chalkboard fa-lg fa-fw"></i> Teaching'
      href: teaching.qmd
    - text: '<i class="fa-brands fa-r-project fa-lg fa-fw"></i> R'
      href: software.qmd
    - text: '<i class="fa-solid fa-note-sticky fa-lg fa-fw"></i> Eviews'
      href: eviews.qmd
    - text: '<i class="fa-solid fa-toolbox fa-lg fa-fw"></i> usesthis'
      href: uses.qmd
    right: 
    - text: '<i class="fa-solid fa-at fa-lg fa-fw"></i>'
      href: "mailto:eer@eremrah.com"
      aria-label: Mail
      target: _blank
      rel: me
    - text: '<i class="fa-brands fa-bluesky fa-lg fa-fw"></i>'
      href: "https://bsky.app/profile/emraher.bsky.social"
      aria-label: Bluesky
      target: _blank
      rel: me
    - text: '<i class="fa-brands fa-mastodon fa-lg fa-fw"></i>'
      href: "https://econtwitter.net/@emraher"
      aria-label: Mastodon
      target: _blank
      rel: me
    - text: '<i class="fa-brands fa-x-twitter fa-lg fa-fw"></i>'
      href: "https://twitter.com/emrah_er"
      aria-label: Twitter
      target: _blank
      rel: me
    - text: '<i class="fa-brands fa-github fa-lg fa-fw"></i>'
      href: "https://github.com/emraher"
      aria-label: Github
      target: _blank
      rel: me
    - text: '<i class="fa-brands fa-orcid fa-lg fa-fw"></i>'
      href: "https://orcid.org/0000-0001-9909-7479"
      aria-label: Orcid
      target: _blank
      rel: me
    - text: '<i class="fa-brands fa-keybase fa-lg fa-fw"></i>'
      href: "https://keybase.io/emraher"
      aria-label: Keybase
      target: _blank
      rel: me

format:
  html:
    theme: [cosmo, styles.scss]
    toc: false
    minimal: true
    html-math-method: mathjax
    include-in-header: fontawesome.html
    mainfont: Merriweather
    monofont: JetBrains Mono
    fontsize: 1rem
    linestretch: 1.75
    